services:
  etl-stable:
    container_name: etl-public
    image: oksii/etlegacy:stable
    env_file: .env
    environment:
      - "HOSTNAME=Polish ET Legacy Public"
    volumes:
      - ./maps:/maps
      - ./move-config.sh:/move-config.sh
    ports:
      - "27960:27960/udp"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "com.centurylinklabs.watchtower.lifecycle.pre-update=/legacy/server/autorestart"
    entrypoint: ["/bin/bash", "/move-config.sh"]
    stdin_open: true
    tty: true
    restart: unless-stopped

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    env_file: .env
    command: --http-api-update --enable-lifecycle-hooks
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config.json:/config.json
    environment:
      - WATCHTOWER_HTTP_API_TOKEN=$WATCHTOWER_API_TOKEN
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
      - "com.watchtower=watchtower"
    ports:
      - 8080:8080
