services:
  etl-stable:
    container_name: etl-public
    build:
      context: .
      dockerfile: Dockerfile
      args:
        STATIC_URL_AMD64: ${STATIC_URL_AMD64}
        STATIC_URL_ARM64: ${STATIC_URL_ARM64}
    env_file: .env
    environment:
      - "HOSTNAME=^7Pol^1ish ET ^7Legacy Public hosted in .de"
    volumes:
      - ./maps:/maps
      - ./homepath:/legacy/homepath:rw
    ports:
      - "27962:27962/udp"
    stdin_open: true
    tty: true
    restart: unless-stopped
